apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h0m0s
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: latest
spec:
  releaseName: kyverno
  interval: 1h0m0s
  chart:
    spec:
      chart: kyverno
      version: 3.0.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
  values:
    podAnnotations:
      ad.datadoghq.com/kyverno.check_names: '["openmetrics"]'
      ad.datadoghq.com/kyverno.init_configs: '[{}]'
      ad.datadoghq.com/kyverno.instances: '[{"prometheus_url": "http://kyverno-svc-metrics.kyverno.svc.cluster.local:8000/metrics","namespace": "kyverno","max_returned_metrics":"10000", "metrics": ["kyverno_policy_rule_info_total","kyverno_admission_requests", "kyverno_policy_changes", "kyverno_policy_results_total"]}]'
    installCRDs: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    replicaCount: 3
    hostNetwork: ${hostNetwork}
    config:
      webhooks:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - twistlock
    resources:
      # -- Pod resource limits
      limits:
        memory: 2048Mi
      # -- Pod resource requests
      requests:
        cpu: 1000m
        memory: 512Mi
    tolerations:
      - key: "admin"
        operator: "Exists"
        effect: "NoExecute"
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                  - admin
          weight: 100
    excludeKyvernoNamespace: true
